services:
  nginx:
    image: nginx:1.27-perl
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.4.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - "3306:3306"
    restart: always

  adminer:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - "81:8080"
    restart: always

  minio:
    image: minio/minio:RELEASE.2024-05-28T17-19-04Z.fips
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASS}
    restart: always

  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--requirepass", "$REDIS_PASS", "--appendonly", "yes"]
    environment:
      REDIS_PASS: ${REDIS_PASS}
    restart: always

volumes:
  db_data:
  minio-data:
  redis-data:
